Personal models
TmLev/dal pull request #184
Opened 2021-02-12 08:36 UTC by alexsivkovu

2021-02-12 08:42 UTC, TmLev requested changes

2021-02-12 08:42 UTC, TmLev commented on back-end/common/models/persons.py
> +    photo = models.ImageField(upload_to='', max_length=128)
@gakhromov decide already.

2021-02-12 08:42 UTC, TmLev commented on back-end/common/models/persons.py
> +                     ('sister', 'сестра'), ('brother', 'брат')]
TODO for later: export to `TextChoices`.

2021-02-12 08:42 UTC, TmLev commented on back-end/lms/models/student.py
> +                   ('deducted', 'отчислен'), ('enrollee', 'абитуриент')]
TODO as above.

2021-02-12 08:42 UTC, TmLev commented on back-end/lms/views/populate.py
> +            'date': '2020-09-04',
Restore @gakhromov's `datetime` dates everywhere, please.

2021-02-12 09:22 UTC, vladisa88 commented on back-end/lms/views/populate.py
> +        typ, _ = AchievementType.objects.get_or_create(achievement_type=value)
Why do you create `AchivementType` object here? I think it should be `MilSpeciality` instead

2021-03-07 15:03 UTC, gakhromov approved these changes
Apart from changing lists to `TextChoices`, everything looks good to me. Don't think we have to change it rn, so lets merge this thing.

2021-03-07 16:39 UTC, TmLev approved these changes

2021-03-07 16:40 UTC, merged