Add student info page back-end
TmLev/dal pull request #335
Opened 2021-07-03 13:07 UTC by vladisa88

2021-07-03 13:35 UTC, gakhromov requested changes
Address my comments.

2021-07-03 13:35 UTC, gakhromov commented on back-end/src/lms/filters/punishments.py
Remove comma

2021-07-03 13:35 UTC, gakhromov commented on back-end/src/lms/views/dashboard.py
> +        for lesson in lessons:
`*` ?

2021-07-03 13:44 UTC, gakhromov approved these changes
LGTM

2021-07-03 13:48 UTC, gakhromov approved these changes

2021-07-05 15:11 UTC, TmLev commented
Merged in #333.

2021-07-05 15:11 UTC, closed without merging